### ISSUE TITLE
Initial GraphQL and Seeds

### ISSUE THREAD

**Issue by Jesse-Lemieux** [Jesse-Lemieux/giv#2]
## Description:
- Set up back end server for GraphQL
- Add seeders to populate data for react structuring 
- Prepopulate users with points(for development)
- Implement seed.js functionality

**Comment by noreikam** [comment]
Wrote seeds for category, cause, and user.  Unable to test bc of server bugs.  Pushed code to feature/backend-setup for time being, will not merge to develop until bugs are resolved.
