### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Jesse-Lemieux** [Jesse-Lemieux/giv#4]
## Description:
Following classes required:

## User:
- Username: String
- Email: Matched string
- Password: String (define params)
- CharityInterest?: [??]
- Points: Integer
- TotalDonations: Integer(Keeps track of total user donations)

## Cause:
- Title: String
- Description: String
- Link: Required
- Location: String
- Category: Assigned from populated
- Medals: [ ?? ]
- Points: Integer (Legacy)
- Comments: [ ?? ]

## Share:
- Title: String
- Link: { Cause }

## Point:
- CauseId: { Cause }
- UserId: { User }

**Comment by noreikam** [comment]
Built models for User, Cause, Share, Point, Medal, and Category on branch feature/backend-setup
